language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run python setup.py install
script:
  - pipenv run yapf --diff --recursive .
